source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#pod 'MBProgressHUD', '~> 0.8'
pod 'MSDynamicsDrawerViewController'
pod 'DZNSegmentedControl', :head
pod "UIImageView-Letters"
pod 'SVProgressHUD'
pod 'NSDate+TimeAgo'
