source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'SGNavigationProgress'
pod 'AFNetworking', '~> 2.0'
pod 'JBChartView', '~> 2.5.5'
pod "RMDateSelectionViewController", "~> 1.4.0"

