source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'SGNavigationProgress'
pod 'AFNetworking', '~> 2.0'
pod "RMDateSelectionViewController", "~> 1.4.0"
pod 'DZNSegmentedControl', :head
pod "UIImageView-Letters"
pod 'SVProgressHUD'
pod 'NSDate+TimeAgo'
pod 'MSDynamicsDrawerViewController'
